export type ValidProp =
  | 'type'
  | 'name'
  | 'subgroup'
  | 'icon'
  | 'stack_size'
  | 'hidden'
  | 'weight'
  | 'ingredient_to_weight_coefficient'
  | 'fuel_category'
  | 'fuel_value'

  | 'category'
  | 'ingredients'
  | 'energy_required'
  | 'results'
  | 'allow_productivity'
  | 'temperature'
  | 'amount'
  | 'probability'
  | 'surface_conditions'
  | 'property'
  | 'min'
  | 'max'

  | 'base_color'
  | 'flow_color'
  | 'auto_barrel'
